CREATE TABLE companies(id INTEGER PRIMARY KEY,name TEXT NOT NULL,slug TEXT UNIQUE NOT NULL,currency TEXT NOT NULL DEFAULT 'SAR',active INTEGER NOT NULL DEFAULT 1,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO companies(id,name,slug,currency) SELECT 1,name,'legacy-company',currency FROM company WHERE id=1;
ALTER TABLE users ADD COLUMN company_id INTEGER REFERENCES companies(id);
UPDATE users SET company_id=1 WHERE company_id IS NULL AND EXISTS (SELECT 1 FROM companies WHERE id=1);
ALTER TABLE partners ADD COLUMN company_id INTEGER REFERENCES companies(id);
ALTER TABLE products ADD COLUMN company_id INTEGER REFERENCES companies(id);
ALTER TABLE accounts ADD COLUMN company_id INTEGER REFERENCES companies(id);
ALTER TABLE fiscal_periods ADD COLUMN company_id INTEGER REFERENCES companies(id);
ALTER TABLE journals ADD COLUMN company_id INTEGER REFERENCES companies(id);
ALTER TABLE sales_orders ADD COLUMN company_id INTEGER REFERENCES companies(id);
ALTER TABLE inventory_moves ADD COLUMN company_id INTEGER REFERENCES companies(id);
ALTER TABLE purchase_orders ADD COLUMN company_id INTEGER REFERENCES companies(id);
ALTER TABLE employees ADD COLUMN company_id INTEGER REFERENCES companies(id);
UPDATE partners SET company_id=1 WHERE company_id IS NULL AND EXISTS (SELECT 1 FROM companies WHERE id=1);
UPDATE products SET company_id=1 WHERE company_id IS NULL AND EXISTS (SELECT 1 FROM companies WHERE id=1);
UPDATE accounts SET company_id=1 WHERE company_id IS NULL AND EXISTS (SELECT 1 FROM companies WHERE id=1);
UPDATE fiscal_periods SET company_id=1 WHERE company_id IS NULL AND EXISTS (SELECT 1 FROM companies WHERE id=1);
UPDATE journals SET company_id=1 WHERE company_id IS NULL AND EXISTS (SELECT 1 FROM companies WHERE id=1);
UPDATE sales_orders SET company_id=1 WHERE company_id IS NULL AND EXISTS (SELECT 1 FROM companies WHERE id=1);
UPDATE inventory_moves SET company_id=1 WHERE company_id IS NULL AND EXISTS (SELECT 1 FROM companies WHERE id=1);
UPDATE purchase_orders SET company_id=1 WHERE company_id IS NULL AND EXISTS (SELECT 1 FROM companies WHERE id=1);
UPDATE employees SET company_id=1 WHERE company_id IS NULL AND EXISTS (SELECT 1 FROM companies WHERE id=1);
